### ISSUE TITLE
[agmod] Snapshot does not work

### ISSUE THREAD

**Issue by FreeSlave** [nekonomicon/hlsdk-xash3d#3]
Can't make screenshot nor via keybinding, nor via direct console command 'snapshot'.

**Comment by nekonomicon** [comment]
Not a bug. This command will be erased on server side https://github.com/nekonomicon/hlsdk-xash3d/blob/aghl/dlls/aghl/agcommand.cpp#L329
You can type `snapshot <random symbols>` to prevent it.
